name: Bug Report
description: Create a report to help us improve
title: "[BUG]: "
labels: ["bug"]
assignees: [""]

body:
  # - type: markdown
  #   attributes:
  #     value: |
  #       Thanks for taking the time to fill out this bug report!!!
  - type: checkboxes
    id: new-bug
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: |
        Give a clear and concise description of what the bug is.
        Point out briefly:
        - What part of the it affects.
        - How it affects the program.
        - Under which apparent conditions it happens.
    validations:
      required: true
  - type: textarea
    id: behaviour-expected
    attributes:
      label: Expected Behaviour
      description: What should happen?
    validations:
      required: true
  - type: textarea
    id: behaviour-actual
    attributes:
      label: Actual Behaviour
      description: What really happen? You can repeat with more details what you wrote in the bug description
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: upload
    id: screenshot
    attributes:
      label: Screenshots
      description: Attach a screenshot of the problem, if applicable.
    validations:
      required: false
      accept: .png, .jpg, .jpeg, .gif, .svg, .webp
  - type: dropdown
    id: os
    attributes:
      label: In which operative system are you running the program?
      description:
      multiple: false
      options:
        - Linux
        - BSD
        - Windows
        - MacOS
    validations:
      required: true
  - type: dropdown
    id: arch
    attributes:
      label: In which architecture are you running the program?
      description:
      multiple: false
      options:
        - x86_64
        - x86
        - Apple Silicon
        - ARM64
        - ARMHF
        - ARMEL
        - RISC-V
    validations:
      required: true
  - type: dropdown
    id: stage
    attributes:
      label: Which is the stage of the program?
      description:
      multiple: false
      options:
        - Alpha
        - Beta
        - Gamma
        - Delta
    validations:
      required: true

